server:
  port: 9095

info:
  artifactId: "spring-cloud-launcher-h2"
  description: "Spring Cloud Launcher H2"
  version: "1.2.0.BUILD-SNAPSHOT"

eureka:
  instance:
    # port of the h2 console
    non-secure-port: 9095
    status-page-url-path: / #allows you to click on the link in eureka dashboard

