server:
  port: 9393

eureka:
  instance:
    status-page-url-path: /admin-ui #allows you to click on the link in eureka dashboard

info:
  artifactId: "spring-cloud-launcher-dataflow"
  description: "Spring Cloud Launcher Data Flow"
  version: "1.2.0.BUILD-SNAPSHOT"

security:
  basic:
    enabled: false

management:
  context-path: /admin
  security:
    enabled: false